/* ========================================================================
 * Copyright 2014 MarketplaceGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 MarketplaceGroup

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.MarketplaceGroup.cart.master.persistence.entity;

import co.edu.uniandes.csw.MarketplaceGroup.item.persistence.entity.ItemEntity;
import co.edu.uniandes.csw.MarketplaceGroup.cart.persistence.entity.CartEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(CartitemEntityId.class)
@NamedQueries({
    @NamedQuery(name = "CartitemEntity.getByMasterId", query = "SELECT  u FROM CartitemEntity u WHERE u.cartId=:cartId"),
    @NamedQuery(name = "CartitemEntity.deleteCartitemEntity", query = "DELETE FROM CartitemEntity u WHERE u.cartId=:cartId and  u.itemId=:itemId")
})
public class CartitemEntity implements Serializable {

    @Id
    @Column(name = "cartId")
    private Long cartId;
    @Id
    @Column(name = "itemId")
    private Long itemId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "cartId", referencedColumnName = "id")
    @JoinFetch
    private ItemEntity cartIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "itemId", referencedColumnName = "id")
    @JoinFetch
    private ItemEntity itemIdEntity; 

    public CartitemEntity() {
    }

    public CartitemEntity(Long cartId, Long itemId) {
        this.cartId =cartId;
        this.itemId = itemId;
    }

    public Long getCartId() {
        return cartId;
    }

    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public ItemEntity getCartIdEntity() {
        return cartIdEntity;
    }

    public void setCartIdEntity(ItemEntity cartIdEntity) {
        this.cartIdEntity = cartIdEntity;
    }

    public ItemEntity getItemIdEntity() {
        return itemIdEntity;
    }

    public void setItemIdEntity(ItemEntity itemIdEntity) {
        this.itemIdEntity = itemIdEntity;
    }

}
