/* ========================================================================
 * Copyright 2014 MarketplaceGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 MarketplaceGroup

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.MarketplaceGroup.cart.master.persistence;
import co.edu.uniandes.csw.MarketplaceGroup.item.logic.dto.ItemDTO;
import co.edu.uniandes.csw.MarketplaceGroup.cart.master.persistence.entity.CartitemEntity;
import co.edu.uniandes.csw.MarketplaceGroup.item.persistence.converter.ItemConverter;
import co.edu.uniandes.csw.MarketplaceGroup.cart.logic.dto.CartDTO;
import co.edu.uniandes.csw.MarketplaceGroup.cart.master.logic.dto.CartMasterDTO;
import co.edu.uniandes.csw.MarketplaceGroup.cart.master.persistence.api._ICartMasterPersistence;
import co.edu.uniandes.csw.MarketplaceGroup.cart.persistence.api.ICartPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _CartMasterPersistence implements _ICartMasterPersistence {

  	@PersistenceContext(unitName="MarketplaceProjectPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ICartPersistence cartPersistence;  

    public CartMasterDTO getCart(Long cartId) {
        CartMasterDTO cartMasterDTO = new CartMasterDTO();
        CartDTO cart = cartPersistence.getCart(cartId);
        cartMasterDTO.setCartEntity(cart);
        cartMasterDTO.setListitem(getCartitemEntityList(cartId));
        return cartMasterDTO;
    }

    public CartitemEntity createCartitemEntity(CartitemEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteCartitemEntity(Long cartId, Long itemId) {
        Query q = entityManager.createNamedQuery("CartitemEntity.deleteCartitemEntity");
        q.setParameter("cartId", cartId);
        q.setParameter("itemId", itemId);
        q.executeUpdate();
    }

    public List<ItemDTO> getCartitemEntityList(Long cartId) {
        ArrayList<ItemDTO> resp = new ArrayList<ItemDTO>();
        Query q = entityManager.createNamedQuery("CartitemEntity.getByMasterId");
        q.setParameter("cartId",cartId);
        List<CartitemEntity> qResult =  q.getResultList();
        for (CartitemEntity entity : qResult) { 
            if(entity.getItemIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ItemConverter.entity2PersistenceDTO(entity.getItemIdEntity()));
        }
        return resp;
    }

}
