/* ========================================================================
 * Copyright 2014 MarketplaceGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 MarketplaceGroup

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.MarketplaceGroup.product.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.MarketplaceGroup.product.logic.dto.ProductDTO;
import co.edu.uniandes.csw.MarketplaceGroup.product.logic.dto.ProductPageDTO;
import co.edu.uniandes.csw.MarketplaceGroup.product.logic.api._IProductLogicService;
import co.edu.uniandes.csw.MarketplaceGroup.product.persistence.api.IProductPersistence;

public abstract class _ProductLogicService implements _IProductLogicService {

	@Inject
	protected IProductPersistence persistance;

	public ProductDTO createProduct(ProductDTO product){
		return persistance.createProduct( product); 
    }

	public List<ProductDTO> getProducts(){
		return persistance.getProducts(); 
	}

	public ProductPageDTO getProducts(Integer page, Integer maxRecords){
		return persistance.getProducts(page, maxRecords); 
	}

	public ProductDTO getProduct(Long id){
		return persistance.getProduct(id); 
	}

	public void deleteProduct(Long id){
	    persistance.deleteProduct(id); 
	}

	public void updateProduct(ProductDTO product){
	    persistance.updateProduct(product); 
	}	
}