/* ========================================================================
 * Copyright 2014 MarketplaceGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 MarketplaceGroup

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.MarketplaceGroup.cart.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.MarketplaceGroup.cart.logic.dto.CartDTO;
import co.edu.uniandes.csw.MarketplaceGroup.cart.logic.api.ICartLogicService;
import co.edu.uniandes.csw.MarketplaceGroup.cart.master.logic.api._ICartMasterLogicService;
import co.edu.uniandes.csw.MarketplaceGroup.cart.master.logic.dto.CartMasterDTO;
import co.edu.uniandes.csw.MarketplaceGroup.item.logic.api.IItemLogicService;
import co.edu.uniandes.csw.MarketplaceGroup.item.logic.dto.ItemDTO;
import javax.inject.Inject;


public abstract class _CartMasterMockLogicService implements _ICartMasterLogicService {

    protected static ArrayList<CartMasterDTO> cartMasterDtosList = new ArrayList<CartMasterDTO>() ;
    @Inject
    protected IItemLogicService itemPersistance;
    @Inject
    protected ICartLogicService cartPersistance;

    public CartMasterDTO createMasterCart(CartMasterDTO cart) {

        cartPersistance.createCart(cart.getCartEntity());
        for (ItemDTO dto : cart.getCreateitem()) {
            itemPersistance.createItem(dto);
        }
        cartMasterDtosList.add(cart);
        return cart;
    }

    public CartMasterDTO getMasterCart(Long id) {
        for (CartMasterDTO cartMasterDTO : cartMasterDtosList) {
            if (cartMasterDTO.getCartEntity().getId() == id) {
                return cartMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterCart(Long id) {
        for (CartMasterDTO cartMasterDTO : cartMasterDtosList) {
            if (cartMasterDTO.getCartEntity().getId() == id) {

                for (ItemDTO dto : cartMasterDTO.getCreateitem()) {
                    itemPersistance.deleteItem(dto.getId());
                }
                cartPersistance.deleteCart(cartMasterDTO.getId());
                cartMasterDtosList.remove(cartMasterDTO);
            }
        }

    }

    public void updateMasterCart(CartMasterDTO cart) {

        // update Item
        if (cart.getUpdateitem() != null) {
            for (ItemDTO dto : cart.getUpdateitem()) {
                itemPersistance.updateItem(dto);
            }
        }
        // persist new Item
        if (cart.getCreateitem() != null) {
            for (ItemDTO dto : cart.getCreateitem()) {
                ItemDTO persistedItemDTO = itemPersistance.createItem(dto);
                dto = persistedItemDTO;
            }
        }
        // delete Item
        if (cart.getDeleteitem() != null) {
            for (ItemDTO dto : cart.getDeleteitem()) {

                itemPersistance.deleteItem(dto.getId());
            }
        }
    }
}