/* ========================================================================
 * Copyright 2014 MarketplaceGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 MarketplaceGroup

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.qualifier

*/

package co.edu.uniandes.csw.MarketplaceGroup.cart.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.MarketplaceGroup.cart.logic.dto.CartDTO;
import co.edu.uniandes.csw.MarketplaceGroup.cart.logic.dto.CartPageDTO;
import co.edu.uniandes.csw.MarketplaceGroup.cart.logic.api._ICartLogicService;
import co.edu.uniandes.csw.MarketplaceGroup.cart.persistence.api.ICartPersistence;

public abstract class _CartLogicService implements _ICartLogicService {

	@Inject
	protected ICartPersistence persistance;

	public CartDTO createCart(CartDTO cart){
		return persistance.createCart( cart); 
    }

	public List<CartDTO> getCarts(){
		return persistance.getCarts(); 
	}

	public CartPageDTO getCarts(Integer page, Integer maxRecords){
		return persistance.getCarts(page, maxRecords); 
	}

	public CartDTO getCart(Long id){
		return persistance.getCart(id); 
	}

	public void deleteCart(Long id){
	    persistance.deleteCart(id); 
	}

	public void updateCart(CartDTO cart){
	    persistance.updateCart(cart); 
	}	
}